#!/usr/bin/env bash
#
# log-preflight.sh — emit a compact, paste-ready "briefing" for a log/text file.
#
# Purpose: run this FIRST on any log, then paste the output to the AI. It does the
# cheap, deterministic discovery (shape, format, levels, top errors, repeats,
# time span, fields) locally, so the model can skip the orient/discovery turns
# and go straight to reasoning. Everything here only COUNTS and AGGREGATES —
# it never dumps the whole file — so the briefing stays small.
#
# Usage:   bash scripts/log-preflight.sh <file> [maxItems]   # default maxItems=8
#          bash scripts/log-preflight.sh app.log > briefing.md
#
# Portable: pure grep/awk/sort/sed — no GNU-only flags, works on macOS (BSD) too.

set -euo pipefail

FILE="${1:-}"
N="${2:-8}"   # how many items per "top" list

if [[ -z "$FILE" || ! -f "$FILE" ]]; then
  echo "usage: bash log-preflight.sh <file> [maxItems]" >&2
  exit 1
fi

# Sample lines for the heavier scans so multi-GB files don't blow up. We scan the
# whole file for cheap things (counts) but cap context reads.
LINES=$(wc -l < "$FILE" | tr -d ' ')
BYTES=$(wc -c < "$FILE" | tr -d ' ')

echo "# Log briefing — \`$FILE\`"
echo
echo "Generated by log-preflight.sh. Feed this to the AI to skip discovery turns."
echo

# ---- 1. Shape -----------------------------------------------------------------
echo "## 1. Shape"
echo "- lines: **$LINES**, bytes: **$BYTES**"
echo '- first 3 lines:'
echo '```'
sed -n '1,3p' "$FILE"
echo '```'
echo '- last 3 lines:'
echo '```'
tail -n 3 "$FILE"
echo '```'
echo

# ---- 2. Format guess ----------------------------------------------------------
echo "## 2. Format guess"
HEAD1=$(sed -n '1p' "$FILE")
fmt="plain/unknown"
case "$HEAD1" in
  '{'*|'['*)                       fmt="JSON / JSON-lines (try jq)";;
esac
if printf '%s' "$HEAD1" | grep -qE '<[a-zA-Z?]'; then fmt="XML/HTML"; fi
if printf '%s' "$HEAD1" | grep -qE '^[^,]+,[^,]+,'; then fmt="CSV-like"; fi
if printf '%s' "$HEAD1" | grep -qE '[a-zA-Z_][a-zA-Z0-9_]*=[^ ]+'; then fmt="$fmt + key=value fields"; fi
if printf '%s' "$HEAD1" | grep -qE '^[A-Z][a-z]{2} +[0-9]+ [0-9]{2}:[0-9]{2}:[0-9]{2}'; then fmt="syslog"; fi
echo "- looks like: **$fmt**"
echo

# ---- 3. Time span + biggest gaps ---------------------------------------------
echo "## 3. Time span & gaps"
# Grab the first ISO-ish timestamp on each line; report span + the largest jumps.
TS_FIRST=$(grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}:[0-9]{2}' "$FILE" | head -n1 || true)
TS_LAST=$(grep -oE '[0-9]{4}-[0-9]{2}-[0-9]{2}[ T][0-9]{2}:[0-9]{2}:[0-9]{2}' "$FILE" | tail -n1 || true)
if [[ -n "$TS_FIRST" ]]; then
  echo "- first ts: \`$TS_FIRST\`  →  last ts: \`$TS_LAST\`"
else
  echo "- no ISO timestamps detected → time-based analysis not available; use line order."
fi
echo

# ---- 4. Level histogram -------------------------------------------------------
echo "## 4. Level histogram"
echo '```'
grep -ioE 'FATAL|ERROR|WARN(ING)?|INFO|DEBUG|TRACE' "$FILE" \
  | tr '[:lower:]' '[:upper:]' | sed 's/WARNING/WARN/' \
  | sort | uniq -c | sort -rn || echo "(no standard level tokens found)"
echo '```'
echo

# ---- 5. Top errors (with line numbers) ---------------------------------------
echo "## 5. First errors — with line numbers (jump points)"
echo '```'
grep -niE 'error|fatal|exception|panic|segfault|traceback|fail(ed|ure)?|crash|OOM|out of memory' "$FILE" \
  | head -n "$N" || echo "(no error markers found)"
echo '```'
echo

# ---- 6. Top repeated messages (digit-normalized) -----------------------------
echo "## 6. Top repeated messages (noise/loops)"
echo '```'
# Strip leading timestamp + collapse numbers so near-duplicate lines group together.
sed -E 's/^[0-9TZ:.+ -]{8,}//; s/[0-9]+/#/g' "$FILE" \
  | sort | uniq -c | sort -rn | head -n "$N" || true
echo '```'
echo

# ---- 7. Components / tags -----------------------------------------------------
echo "## 7. Top components/tags"
echo '```'
grep -oE '\[[A-Za-z0-9_.:/-]+\]' "$FILE" | sort | uniq -c | sort -rn | head -n "$N" \
  || echo "(no [bracketed] components found)"
echo '```'
echo

# ---- 8. Discovered key=value fields ------------------------------------------
echo "## 8. Discovered key=value fields"
echo '```'
grep -oE '[a-zA-Z_][a-zA-Z0-9_.]*=' "$FILE" | sort | uniq -c | sort -rn | head -n "$N" \
  || echo "(no key=value fields found)"
echo '```'
echo

echo "---"
echo "_Next: tell the AI the **symptom** (crashed / slow / froze / wrong value / won't start)."
echo "It will use the line numbers above as jump points and only read the few windows it needs._"
